services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: ghcr.io/koenkk/zigbee2mqtt:1.25.0
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/London
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - mosquitto
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.14
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
    command: "mosquitto -c /mosquitto-no-auth.conf"
  home_assistant:
    container_name: home_assistant
    image: ghcr.io/home-assistant/home-assistant:2022.4.7
    restart: unless-stopped
    volumes:
      - ./home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:8123 
