# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

influxdb:
  api_version: 2
  token: !secret influxdb_token
  organization: 957eb6e450158b73
  host: influxdb
  port: 8086
  bucket: home_assistant
  ssl: false
