permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://mosquitto
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
availability: true
advanced:
  network_key: '!secret network_key'
homeassistant: true
devices:
  '0x00158d0007b6dd8d':
    friendly_name: living_room/air_sensor
  '0x00158d0007b6f306':
    friendly_name: bedroom_1/air_sensor
  '0x00158d0007df636d':
    friendly_name: office/air_sensor
  '0x00158d0007df64c4':
    friendly_name: bathroom/air_sensor
  '0x00158d0007bc12a8':
    friendly_name: bedroom_2/air_sensor
  '0x00158d0007b6f469':
    friendly_name: kitchen/air_sensor
  '0x00158d0007bc16bc':
    friendly_name: dining_room/air_sensor
  '0x00158d0007bc1813':
    friendly_name: garage/air_sensor
  '0x00158d0007df98ec':
    friendly_name: porch/air_sensor
  '0x0017880106f555cf':
    friendly_name: garage/motion_sensor
  '0x001788010472afc7':
    friendly_name: garage/light
  '0x001788010472b007':
    friendly_name: hallway/entrance_light
